export const HOME_ROUTE = 'HOME_ROUTE';
export const ADD_CLIENT_ROUTE = 'ADD_CLIENT_ROUTE';
export const PROFILE_CLIENT_ROUTE = 'PROFILE_CLIENT_ROUTE';
export const EDIT_CLIENT_ROUTE = 'EDIT_CLIENT_ROUTE';
export const EDIT_PARENTS_CLIENT_ROUTE = 'EDIT_PARENTS_CLIENT_ROUTE';
export const ALL_CLIENTS_ROUTE = 'ALL_CLIENTS_ROUTE';
export const AUTH_ADMIN_IN_APP = 'AUTH_ADMIN_IN_APP';
export const STUFF_ROUTE = 'STUFF_ROUTE';

export const CREATE_AND_EDIT_LESSONS = 'CREATE_AND_EDIT_LESSONS';
export const SETTINGS_APP_ROUTE = 'SETTINGS_APP_ROUTE';
export const SETTINGS_GROUP = 'SETTINGS_GROUP';

export const SETTINGS_AGE_GROUP_CREATE = 'SETTINGS_AGE_GROUP_CREATE';
export const SETTINGS_GROUP_CREATE = 'SETTINGS_GROUP_CREATE';
export const SETTINGS_GROUP_EDIT = 'SETTINGS_GROUP_EDIT';

export const SETTINGS_STATUS = 'SETTINGS_STATUS';
export const SETTINGS_STATUS_CREATE = 'SETTINGS_STATUS_CREATE';
export const SETTINGS_STATUS_EDIT = 'SETTINGS_STATUS_EDIT';

export const SETTINTS_SALES_LIST = 'SETTINTS_SALES_LIST';
export const SETTINTS_SALES_LIST_CREATE = 'SETTINTS_SALES_LIST_CREATE';
export const SETTINTS_SALES_LIST_EDIT = 'SETTINTS_SALES_LIST_EDIT';

export const SETTINGS_ABONEMENT = 'SETTINGS_ABONEMENT';
export const SETTINGS_ABONEMENT_VIEW = 'SETTINGS_ABONEMENT_VIEW';
export const SETTINGS_CREATE_ABONEMENT = 'SETTINGS_CREATE_ABONEMENT';
export const SETTINGS_ABONEMENT_EDIT = 'SETTINGS_ABONEMENT_EDIT';

export const REPORTS_GENERAL_ROUTE = 'REPORTS_GENERAL_ROUTE';
export const REPORTS_VISITS_ROUTE = 'REPORTS_VISITS_REPORT_ROUTE';
export const REPORTS_PROCEED_ROUTE = 'REPORTS_PROCEED_REPORT_ROUTE';
export const REPORTS_ABONEMENTS_ROUTE = 'REPORTS_ABONEMENTS_REPORT_ROUTE';
export const REPORTS_CLIENT_ROUTE = 'REPORTS_CLIENT_REPORT_ROUTE';
// export const REPORTS_GENERAL_ROUTE = 'REPORTS_GENERAL_ROUTE';
// export const REPORTS_GENERAL_ROUTE = 'REPORTS_GENERAL_ROUTE';
// export const REPORTS_GENERAL_ROUTE = 'REPORTS_GENERAL_ROUTE';
