export const HOME_ROUTE = 'HOME_ROUTE';
export const ADD_CLIENT_ROUTE = 'ADD_CLIENT_ROUTE';
export const PROFILE_CLIENT_ROUTE = 'PROFILE_CLIENT_ROUTE';
export const EDIT_CLIENT_ROUTE = 'EDIT_CLIENT_ROUTE';
export const ALL_CLIENTS_ROUTE = 'ALL_CLIENTS_ROUTE';
export const SETTINGS_APP_ROUTE = 'SETTINGS_APP_ROUTE';
export const CREATE_AND_EDIT_LESSONS = 'CREATE_AND_EDIT_LESSONS';
export const AUTH_ADMIN_IN_APP = 'AUTH_ADMIN_IN_APP';