export const LOAD_CLIENTS_FOR_ALL = 'LOAD_CLIENTS_FOR_ALL';
export const LOAD_COUCH_FOR_ALL = 'LOAD_COUCH_FOR_ALL';
export const LOAD_GROUP_FOR_ALL = 'LOAD_GROUP_FOR_ALL';
export const LOAD_ABONEMENT_FOR_ALL = 'LOAD_ABONEMENT_FOR_ALL';
export const LOAD_FILIAL_FOR_ALL = 'LOAD_FILIAL_FOR_ALL';
export const LOAD_TYPES_LIST_FOR_ALL = 'LOAD_TYPES_LIST_FOR_ALL';
export const LOAD_STATUS_LIST_FOR_ALL = 'LOAD_STATUS_LIST_FOR_ALL';
export const LOAD_SORT_FOR_ALL = 'LOAD_SORT_FOR_ALL';