export const LOAD_GENERAL_PAGE = 'LOAD_GENERAL_PAGE';

export const LOAD_GENERAL_PAGE_DATA = 'LOAD_GENERAL_PAGE_DATA';
export const LOAD_GENERAL_PAGE_DATA_SUCCESS = 'LOAD_GENERAL_PAGE_DATA_SUCCESS';
export const LOAD_GENERAL_PAGE_DATA_FAILURE = 'LOAD_GENERAL_PAGE_DATA_FAILURE';

export const CHANGE_DATE = 'CHANGE_DATE';
export const SET_DATE = 'SET_DATE';

export const ADD_CLIENT_IN_TRAIN = 'ADD_CLIENT_IN_TRAIN';
export const BUY_AND_ADD_CLIENT_ON_TRAIN = 'BUY_AND_ADD_CLIENT_ON_TRAIN';

export const ABONEMENT_EXPIRE = 'ABONEMENT_EXPIRE';

export const ADD_DEBT_CLIENT_IN_TRAIN = 'ADD_DEBT_CLIENT_IN_TRAIN';
export const ADD_ONCE_CLIENT_IN_TRAIN = 'ADD_ONCE_CLIENT_IN_TRAIN';

export const CHANGE_DATE_FOR_GET_LESSONS = 'CHANGE_DATE_FOR_GET_LESSONS';

export const SEARCH_CLIENTS = 'SEARCH_CLIENTS';

export const CHANGE_TRAINER_FOR_GROUP = 'CHANGE_TRAINER_FOR_GROUP';
// export const LOAD_GENERAL_PAGE_DATA_FAILURE = 'LOAD_GENERAL_PAGE_DATA_FAILURE';

export const REMOVE_CLIENT_FROM_TRAIN = 'REMOVE_CLIENT_FROM_TRAIN';
