export const LOAD_PROFILE_USER = 'LOAD_PROFILE_USER';
export const LOAD_PROFILE_TYPE_ABONIMENT = 'LOAD_PROFILE_TYPE_ABONIMENT';
export const LOAD_PROFILE_STATUS = 'LOAD_PROFILE_STATUS';
export const LOAD_PROFILE_GROUP = 'LOAD_PROFILE_GROUP';
export const LOAD_PROFILE_COUCH = 'LOAD_PROFILE_COUCH';