export const PROCEED_REPORT_PAGE = 'PROCEED_REPORT_PAGE'
export const START_LOAD_DATA_PROCEED_REPORT = 'START_LOAD_DATA_PROCEED_REPORT'
export const DONE_LOAD_DATA_PROCEED_REPORT = 'DONE_LOAD_DATA_PROCEED_REPORT'