export const LOAD_DATA_SOURCE_LIST = 'LOAD_DATA_SOURCE_LIST';
export const SUCCESS_LOAD_DATA_SOURCE_LIST = 'SUCCESS_LOAD_DATA_SOURCE_LIST';
export const CREATE_SOURCE_LIST = 'CREATE_SOURCE_LIST';

export const START_EDIT_SOURCE_LIST = 'START_EDIT_SOURCE_LIST';
export const SUCCESS_EDIT_SOURCE_LIST = 'SUCCESS_EDIT_SOURCE_LIST';
export const EDIT_SOURCE_LIST = 'EDIT_SOURCE_LIST';

export const DELETE_SOURCE_LIST = 'DELETE_SOURCE_LIST';
