export const LOAD_DATA_SOURCE_LIST = 'LOAD_DATA_SOURCE_LIST';
export const SUCCESS_LOAD_DATA_SOURCE_LIST = 'SUCCESS_LOAD_DATA_SOURCE_LIST';
export const CREATE_SOURCE_LIST = 'CREATE_SOURCE_LIST';
export const DELETE_SOURCE_LIST = 'DELETE_SOURCE_LIST';
