export const START_LOAD_DATA_SETTINGS_ABONEMENT = 'START_LOAD_DATA_SETTINGS_ABONEMENT';
export const START_LOAD_DATA_SETTINGS_ABONEMENT_SUCCESS =
	'START_LOAD_DATA_SETTINGS_ABONEMENT_SUCCESS';
export const START_LOAD_DATA_SETTINGS_ABONEMENT_FAILURE =
	'START_LOAD_DATA_SETTINGS_ABONEMENT_FAILURE';

export const START_LOAD_DATA_ABONEMENT = 'START_LOAD_DATA_ABONEMENT';
export const START_LOAD_DATA_ABONEMENT_SUCCESS = 'START_LOAD_DATA_ABONEMENT_SUCCESS';
export const START_LOAD_DATA_ABONEMENT_FAILURE = 'START_LOAD_DATA_ABONEMENT_FAILURE';

export const START_LOAD_STATUS = 'START_LOAD_STATUS';
export const START_LOAD_STATUS_SUCCESS = 'START_LOAD_STATUS_SUCCESS';
export const REMOVE_LEVEL = 'REMOVE_LEVEL';
export const ADD_NEW_STATUS = 'ADD_NEW_STATUS';
export const EDIT_STATUS = 'EDIT_STATUS';
export const EXIT_STATUS_EDIT_PAGE = 'EXIT_STATUS_EDIT_PAGE';

export const UPLOAD_DATA_SETTINGS_ABONEMENT = 'UPLOAD_DATA_SETTINGS_ABONEMENT';
export const EDIT_DATA_SETTINGS_ABONEMENT = 'EDIT_DATA_SETTINGS_ABONEMENT';

export const CLEAR_CURRENT_ABONEMENT = 'CLEAR_CURRENT_ABONEMENT';

export const REMOVE_ABONEMENT = 'REMOVE_ABONEMENT';
